name: 'init'
description: 'Common init action for all workflows. Includes checkout logic.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}
