name: 'init'
description: 'Common init action for all workflows. Includes checkout logic.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}

    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
        cache: true
        cacheHash: ${{ hashFiles('${{ github.action_path }}/../deno.lock') }}

    - name: install action dependencies
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: deno install
