name: 'configure-deployment'

description: 'Configure deployment in a GitOps repository.'

inputs:
  gitops-repo:
    description: 'The GitOps repository to configure deployment in.'
    required: false
    default: ${{ github.repository_owner }}/easygitops
  gitops-repo-token:
    description: 'The token to use to access the GitOps repository.'
    required: true

runs:
  using: "composite"
  steps:

    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: install action dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: deno install

    - uses: actions/checkout@v5
      with:
        repository: ${{ inputs.gitops-repo }}
        token: ${{ inputs.gitops-repo-token }}
        path: gitops-repo

    - shell: bash
      run: ${{ github.action_path }}/test.ts

    - shell: bash
      working-directory: gitops-repo
      run: |
        set -ex
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Configure deployment for ${{ github.repository }}" || echo "No changes to commit"
        git push
        cat $GITHUB_ENV
