name: 'Docker Build & Publish'
description: 'Builds a Docker image and pushes it to GitHub Container Registry with the commit hash as the tag.'
inputs:
  registry:
    description: 'The container registry to push the image to.'
    required: false
    default: 'ghcr.io'
  registry_username:
    description: 'The username for the container registry.'
    required: false
    default: '${{ github.actor }}'
  registry_password:
    description: 'The password or token for the container registry.'
    required: false
    default: '${{ github.token }}'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Build Variables
      id: vars
      shell: bash
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(basename "${{ github.repository }}")
        # Use input if provided, else default to 'app'
        IMAGE_NAME="${{ inputs.image_name }}"
        if [ -z "$IMAGE_NAME" ]; then IMAGE_NAME="app"; fi
        if [ -z "$NEW_RELEASE_VERSION" ]; then
          IMAGE_TAG="${{ github.sha }}"
        else
          IMAGE_TAG="$NEW_RELEASE_VERSION"
        fi
        IMAGE="${{ inputs.registry }}/$REPO_OWNER/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG"
        echo "image=$IMAGE" >> $GITHUB_OUTPUT
  
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build Docker image
      shell: bash
      run: |
        docker build -t "${{ steps.vars.outputs.image }}" .

    - name: Push Docker image
      shell: bash
      run: |
        docker push "${{ steps.vars.outputs.image }}"
