name: 'Docker Build & Publish'
description: 'Builds a Docker image and pushes it to GitHub Container Registry with the commit hash as the tag.'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Build Variables
      id: vars
      shell: bash
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(basename "${{ github.repository }}")
        # Use input if provided, else default to 'app'
        IMAGE_NAME="${{ inputs.image_name }}"
        if [ -z "$IMAGE_NAME" ]; then IMAGE_NAME="app"; fi
        COMMIT_SHA="${{ github.sha }}"
        TAG="ghcr.io/$REPO_OWNER/$REPO_NAME/$IMAGE_NAME:$COMMIT_SHA"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - name: Build Docker image
      shell: bash
      run: |
        docker build -t "${{ steps.vars.outputs.tag }}" .
    - name: Push Docker image
      shell: bash
      run: |
        docker push "${{ steps.vars.outputs.tag }}"