name: 'Semantic Release'
description: 'Run semantic-release with minimal configuration - supports full releases on main and prereleases on other branches'
branding:
  icon: 'tag'
  color: 'green'

inputs:
  dry-run:
    description: 'Run in dry-run mode (no actual release)'
    required: false
    default: 'false'
  working-directory:
    description: 'Working directory to run semantic-release from'
    required: false
    default: '.'

outputs:
  new-release-version:
    description: 'The new release version number (without v prefix)'
  new-release-git-tag:
    description: 'The new release git tag (with v prefix)'
  new-release-published:
    description: 'Whether a new release was published'

runs:
  using: 'node24'
  main: 'dist/index.js'